server:
  port: 8081

spring:
  application:
    name: simple-sso
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:${server.port}
        introspection-endpoint: /oauth2/token-info
      client:
        registration:
          github:
          #clientId: VAULT
          #clientSecret: VAULT
          google:
            #clientId: VAULT
            #clientSecret: VAULT
            scope:
              - email
              - profile
          yandex:
            provider: yandex
            #clientId: VAULT
            #clientSecret: VAULT
            redirect-uri: http://localhost:${server.port}/login/oauth2/code/yandex
            authorizationGrantType: authorization_code
            clientName: Yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-name-attribute: default_email
            userInfoUri: https://login.yandex.ru/info

  datasource:
    url: "jdbc:postgresql://localhost:5432/sso-db"
    username: root
    password: root
    driver-class-name: "org.postgresql.Driver"
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 10
      initialization-fail-timeout: 1
      leak-detection-threshold: 0
      pool-name: "HikariPool-"

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  session:
    timeout: 1800
    redis:
      flush-mode: on_save
      namespace: simple-sso:session
      save-mode: on_set_attribute
  data:
    redis:
      client-type: lettuce
      database: 0
      host: localhost
      port: 6379
      password: sso-redis-root
      lettuce:
        pool:
          max-active: 16
          max-idle: 8

#logging:
#  level:
#    root: DEBUG
#    org.springframework.security: TRACE